"""KB-INPUT-LEX 接入层词表 — 公开 API 门面。

包外代码应只从本模块导入，避免直接依赖 ``input_lex`` 子模块实现文件：

.. code-block:: python

    from xiaozhua_health_agent.input_lex import (
        CorpusBuilder,
        EnrichAudit,
        InputLexEnricher,
        InputLexMatchCorpus,
        LexiconLoader,
        RuleMatcher,
        build_enrich_audit_record_async,
        enrich_agent_input_payload_async,
        load_input_lex_bundle_async,
    )

子模块之间使用子模块直引，勿从本 ``__init__`` 回引，以免循环导入。
"""

from __future__ import annotations

from xiaozhua_health_agent.input_lex.corpus_builder import (
    CorpusBuilder,
    InputLexCorpusBuildError,
    build_match_corpus,
    build_match_corpus_async,
    build_match_corpus_from_mapping,
    build_match_corpus_from_mapping_async,
    merge_normalized_segments,
    normalize_match_text,
)
from xiaozhua_health_agent.input_lex.enrich_service import (
    InputLexEnrichError,
    InputLexEnricher,
    enrich_agent_input_payload_async,
    resolve_input_lex_bundle_async,
)
from xiaozhua_health_agent.input_lex.enrich_audit import (
    DEFAULT_ENRICH_AUDIT_BUILD_OPTIONS,
    EnrichAudit,
    EnrichAuditError,
    build_enrich_audit_record,
    build_enrich_audit_record_async,
    persist_enrich_audit_record,
    persist_enrich_audit_record_async,
    serialize_enrich_audit_record_to_json,
    serialize_enrich_audit_record_to_mapping,
)
from xiaozhua_health_agent.input_lex.input_lex_types import (
    DEFAULT_INPUT_LEX_ENRICH_OPTIONS,
    INPUT_LEX_ENRICH_AUDIT_SCHEMA_VERSION,
    INPUT_LEX_ENRICH_RESULT_SCHEMA_VERSION,
    INPUT_LEX_SCHEMA_VERSION,
    InputLexAppendApplicationRecord,
    InputLexBundle,
    InputLexConflictResolutionLiteral,
    InputLexCorpusAuditSummary,
    InputLexCorpusSegment,
    InputLexEnrichAuditBuildOptions,
    InputLexEnrichOptions,
    InputLexEnrichResult,
    InputLexEnrichAuditPersistOptions,
    InputLexEnrichAuditPersistResult,
    InputLexEnrichAuditRecord,
    InputLexEnumerations,
    InputLexFieldChangeAudit,
    InputLexFieldChangeKindLiteral,
    InputLexMatchCorpus,
    InputLexMatchDefaults,
    InputLexMatchSourceLiteral,
    InputLexMatchedPhraseAudit,
    InputLexMergePolicy,
    InputLexMergeResult,
    InputLexMeta,
    InputLexPatchActionLiteral,
    InputLexPatchApplicationRecord,
    InputLexPatchScalar,
    InputLexPatchSkipReasonLiteral,
    InputLexPhraseMatchDetail,
    InputLexRule,
    InputLexRuleHit,
    InputLexRuleHitAudit,
    InputLexRuleMatch,
    InputLexRuleMatchResult,
    InputLexRuleMergeRecord,
    InputLexRuleModeLiteral,
    InputLexEnrichAuditPersistFormatLiteral,
)
from xiaozhua_health_agent.input_lex.patch_merger import (
    PatchMerger,
    enum_escalation_rank,
    get_nested_field_value,
    is_explicit_ui_value,
    is_lexicon_unknown_value,
    merge_input_lex_patches,
    merge_input_lex_patches_async,
    set_nested_field_value,
)
from xiaozhua_health_agent.input_lex.rule_matcher import (
    RuleMatcher,
    collect_matched_phrases_for_rule,
    match_input_lex_rules,
    match_input_lex_rules_async,
    match_single_input_lex_rule,
    phrase_is_eligible_for_matching,
    phrase_matches_corpus,
    rule_passes_species_filter,
)
from xiaozhua_health_agent.input_lex.lexicon_loader import (
    InputLexLoadError,
    LexiconLoader,
    clear_default_lexicon_loader_cache,
    get_default_lexicon_loader,
    load_input_lex_bundle,
    load_input_lex_bundle_async,
    load_input_lex_bundle_from_json,
    load_input_lex_bundle_from_json_text,
)

__all__ = [
    "DEFAULT_ENRICH_AUDIT_BUILD_OPTIONS",
    "DEFAULT_INPUT_LEX_ENRICH_OPTIONS",
    "INPUT_LEX_ENRICH_AUDIT_SCHEMA_VERSION",
    "INPUT_LEX_ENRICH_RESULT_SCHEMA_VERSION",
    "INPUT_LEX_SCHEMA_VERSION",
    "CorpusBuilder",
    "EnrichAudit",
    "EnrichAuditError",
    "InputLexEnrichError",
    "InputLexEnricher",
    "InputLexEnrichOptions",
    "InputLexEnrichResult",
    "InputLexAppendApplicationRecord",
    "InputLexBundle",
    "InputLexConflictResolutionLiteral",
    "InputLexCorpusAuditSummary",
    "InputLexCorpusBuildError",
    "InputLexCorpusSegment",
    "InputLexEnrichAuditBuildOptions",
    "InputLexEnrichAuditPersistFormatLiteral",
    "InputLexEnrichAuditPersistOptions",
    "InputLexEnrichAuditPersistResult",
    "InputLexEnrichAuditRecord",
    "InputLexEnumerations",
    "InputLexFieldChangeAudit",
    "InputLexFieldChangeKindLiteral",
    "InputLexLoadError",
    "InputLexMatchCorpus",
    "InputLexMatchDefaults",
    "InputLexMatchSourceLiteral",
    "InputLexMatchedPhraseAudit",
    "InputLexMergePolicy",
    "InputLexMergeResult",
    "InputLexMeta",
    "InputLexPatchActionLiteral",
    "InputLexPatchApplicationRecord",
    "InputLexPatchScalar",
    "InputLexPatchSkipReasonLiteral",
    "InputLexPhraseMatchDetail",
    "InputLexRule",
    "InputLexRuleHit",
    "InputLexRuleHitAudit",
    "InputLexRuleMatch",
    "InputLexRuleMatchResult",
    "InputLexRuleMergeRecord",
    "InputLexRuleModeLiteral",
    "LexiconLoader",
    "PatchMerger",
    "RuleMatcher",
    "build_enrich_audit_record",
    "build_enrich_audit_record_async",
    "enrich_agent_input_payload_async",
    "resolve_input_lex_bundle_async",
    "persist_enrich_audit_record",
    "persist_enrich_audit_record_async",
    "serialize_enrich_audit_record_to_json",
    "serialize_enrich_audit_record_to_mapping",
    "enum_escalation_rank",
    "get_nested_field_value",
    "is_explicit_ui_value",
    "is_lexicon_unknown_value",
    "merge_input_lex_patches",
    "merge_input_lex_patches_async",
    "set_nested_field_value",
    "collect_matched_phrases_for_rule",
    "match_input_lex_rules",
    "match_input_lex_rules_async",
    "match_single_input_lex_rule",
    "phrase_is_eligible_for_matching",
    "phrase_matches_corpus",
    "rule_passes_species_filter",
    "build_match_corpus",
    "build_match_corpus_async",
    "build_match_corpus_from_mapping",
    "build_match_corpus_from_mapping_async",
    "clear_default_lexicon_loader_cache",
    "get_default_lexicon_loader",
    "load_input_lex_bundle",
    "load_input_lex_bundle_async",
    "load_input_lex_bundle_from_json",
    "load_input_lex_bundle_from_json_text",
    "merge_normalized_segments",
    "normalize_match_text",
]
